### PR TITLE
Changed original survey-multi-choice plugin to include data for each …

### PR DESCRIPTION
**Pull request by zenkavi**
…question in a separate row.

### CODE REVIEW

**Comment by vsoch** [comment]
Do you know why it's not possible to see changes from the older file? Did you do something strange?

**Comment by zenkavi** [comment]
It's probably because this is a new file. The original plugin is in the plugins directory. This is in the custom_plugins. They work exactly the same except for the data they output

**Comment by vsoch** [comment]
ah, I see. The folder is different. Is this a standard or a custom_plugin? (Before it was in "plugins" I believe)

**Comment by vsoch** [comment]
This guy:

https://github.com/expfactory/expfactory-battery/blob/master/static/js/jspsych/plugins/jspsych-survey-multi-choice.js

**Comment by vsoch** [comment]
It seems confusing to have both - can we choose one? And make sure all the experiments that use the plugin have the paths updated in their config.json

**Comment by zenkavi** [comment]
I created it in the custom_plugins folder and kept the original one in the plugins folder (similar to the jspsych-multi-stim-multi-response.js plugin where there is both an original in the plugins folder and a slightly modified one in the custom_plugins folder)

**Comment by zenkavi** [comment]
It is slightly confusing I agree. I just modeled it based on how the multi-stim-multi-response plugin was placed. The config files specify the correct one and keeping it this way others can simply change the folder there. Do you think that makes sense?

**Comment by vsoch** [comment]
Hmm, I want to suggest that we have a README.md in the custom_plugins folder that, for each custom plugin, details the original functionality, and how the modified one is different. My worry with the current structure / redundancy is that it will get confusing very fast what the custom scripts are doing, and how they are different. Would that be possible to add to this PR?

**Comment by zenkavi** [comment]
That's a great idea and I think we should have it not just for the modified but all the custom_plugins. I'll start it for the plugins i have written or modified mirroring the jspsych documentation as much as I can and add it to the pr

**Comment by vsoch** [comment]
awesome! Now that we have all these updated experiments (45 valid!) I'm going to see if I can update expfactory.github.io. This isn't a huge priority, but I think (soonish) we should switch to some view that can explore tasks based on Cognitive Atlas stuffs.

**Comment by zenkavi** [comment]
@vsoch finished documentation for a bunch of the custom plugins as well as completed updating the custom plug in surveys with new name. Made sure to resolve conflicts with the most recent version of master. Am I missing anything?

**Comment by vsoch** [comment]
I think it looks ok - and this is rebased, etc? @IanEisenberg can you take a look and make sure everything looks ok? When you guys are satisfied, feel free to merge!

**Comment by zenkavi** [comment]
Yes should be rebased. @IanEisenberg let me know if all is good so we can start testing surverys

**Pull request merged**
