### PR TITLE
fixed addID bug in poldrackutils

### PR DESCRIPTION
**Pull request by IanEisenberg**

### CODE REVIEW

**Comment by IanEisenberg** [comment]
I think this might be responsible for the failed check of PR #421. After this gets merged, that PR needs to be rebuilt.

**Comment by vsoch** [comment]
Have you tested and confirmed this?

**Comment by vsoch** [comment]
Also, in order to link fully to a different repo, try copy pasting the full url, eg:

https://github.com/expfactory/expfactory-experiments/pull/421

**Comment by IanEisenberg** [comment]
I always think I have full tested, but when you ask I second guess myself :) Let me test again this afternoon before you merge.

**Comment by vsoch** [comment]
ok sounds good.

**Comment by IanEisenberg** [comment]
Tested, working. Fullscreen detection across browsers/OS's hasn't been extensively tested, but it does work in modern chrome across OS's. Ready to be merged.

**Pull request merged**
