### PR TITLE
Fixed jsyspsych-poldrack-survey-multi-choice.js to correctly display …

### PR DESCRIPTION
**Pull request by zenkavi**
…options that are not horizontal and added parameter survey_name to update data with exp_id variable. Also updated default.css to reflect the styling changes for the plugin and the documentation with the description of the new parameter for the plugin.

### CODE REVIEW

**Comment by vsoch** [comment]
This looks ok to me. Quick clarification: the exp_id variable will always be found in the experiment.js file, correct? That is where I am writing the test to find it.

**Comment by zenkavi** [comment]
each survey so far consists of four blocks: welcome, instructions, survey and end. exp_id will be found in experiment.js for the welcome, instructions and end blocks. for the survey block it will be in the output data which is specified by the survey_name parameter. will that be problematic?

**Comment by vsoch** [comment]
I think "survey_name" should be "exp_id" - is there a reason to have it named "survey_name" (is it a jspsych standard?) I'm still writing and figuring out the test, but generally we always want to have "exp_id" defined when there is a data object.

**Comment by zenkavi** [comment]
@vsoch changed the name of the parameter in the plugin now. let me know if this would work with the tests now or if there are other changes

**Comment by vsoch** [comment]
As long as it's defined in the static experiment.js file, the test will pass. We don't test the plugins.

**Comment by vsoch** [comment]
ok, so for now I think we are decided to hold off adding attention checks variables to the config.json - hard coded in tasks is fine (and I will add this as an enhancement issue when we have time).

If you want to rebase with master to get the updated circle.yml, when the following tests pass:

- definition of exp_id in each experiment
- no jshint errors
- experiment tested in circle.yml defined
- config.json valid

I think those are reasonable criteria for now. Ideally would be having the robot pass all experiments, but it sounds like you guys want to prioritize getting everything merged into one, so we can test the experiments running after.

**Comment by zenkavi** [comment]
no worries. so is this is merge-able?

**Comment by vsoch** [comment]
Make sure it's up to date with master (I don't remember if @IanEisenberg did any changes) and then I think it should be ok. Generally I can't say a lot about the battery files because there are no real tests for it other than if/when experiments work.

**Pull request merged**
