### PR TITLE
possible solution for expfactory/expfactory-surveys#48

### PR DESCRIPTION
**Pull request by IanEisenberg**
Not sure I feel comfortable directly editing the plugin, but these callsbacks seem like they are meant to be customized? Not sure. Anyway, this works, but I imagine there is a better solution.

### CODE REVIEW

**Comment by vsoch** [comment]
Yes, the idea of these callbacks is to provide custom functionality for the user. The command looks good to work - have you tested when this is part of the battery to confirm it works with the different surveys?

**Comment by IanEisenberg** [comment]
If it generally looks good to you I'll go through and test more rigorously.

**Comment by vsoch** [comment]
Definitely a good idea, go for it! :)

**Comment by IanEisenberg** [comment]
Tested on all surveys. Ready to merge.

**Pull request closed without merging**
